name: CodeCov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt 
        
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest Test_Fumagalli_Motta_Tarantino_2020/Test_*.py
        
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
